### ISSUE TITLE
Creates a @UniqueName in Graph API

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql-artemis#42]
Currently, the Graph integrates with Tinkerpop, and that has Id whose some implementation does not allow a defined Id, so:

```java
Guest hillmer = Guest.of("Hillmer");
hillmer = graphTemplate.insert(hillmer);

Guest hillmer2 = Guest.of("Hillmer");
hillmer2 = graphTemplate.insert(hillmer2);

Guest hillmer3 = Guest.of("Hillmer");
hillmer3 = graphTemplate.insert(hillmer3);

```

Inspired by NaturalId from hibernate the goal is create a UniqueName.

So, 

```java
@Entity
public class Guest {
@Id
private Long id;

@UniqueVertexProperty
@Column
private String name;
}
```

So: 

```java
Guest hillmer = Guest.of("Hillmer");
hillmer = graphTemplate.insert(hillmer);

Guest hillmer2 = Guest.of("Hillmer");
hillmer2 = graphTemplate.insert(hillmer2);// an exception because cannot insert twice

```
* https://docs.jboss.org/hibernate/orm/5.0/mappingGuide/en-US/html/ch07.html
* https://www.thoughts-on-java.org/naturalid-good-way-persist-natural-ids-hibernate/

**Comment by Hilmerc** [comment]
UniqueVertexProperty could work but if the developer don't use it,  an unexpected behavior can happen. For our example maybe can be necessary to create the 3 hillmer, suppose they are three different persons with the same name, if you go directly to database as Neo4J you can create the three, is the same with the API. 

The problem is not in creation moment, but when we access and use the vertex. Maybe we need the second Hillmer but the system return the first.

I have a new idea. The method `VertexTraversal.next()` return only one Element even though if more than one match with the filters, but the user is waiting for only one. What do you think to throw an Exception when more than one elements match? 

So

    graphTemplate.getTraversalVertex().hasLabel("Guest")
     .has("name", "hillmer").next(); 
    // an exception because there are three Vertex matching with name hillmer

**Comment by Hilmerc** [comment]
I agree with the method `getSingleResult()`  , and what about to add too  `getResultList()`?. 

Other useful method could be one which return a Vertex finding by @Id, something like   

    graphTemplate.getTraversalVertex().hasLabel("Guest").find(id); 

So, in the cases when more than one could vertex match find some label's values, the user can use the find method to be sure they get the vertex that they need

**Comment by otaviojava** [comment]
Nice, @Hilmerc I created a PR to solve this:

https://github.com/eclipse/jnosql-artemis-extension/pull/18

**Comment by otaviojava** [comment]
About the find by Id, what do you think if we create a new issue to this?

**Comment by otaviojava** [comment]
I'll close this one, however, feel free to open again if necessary.

Thank you @Hilmerc
